### ISSUE TITLE
Icon for colors can't be found, looking for directory that does not exist

### ISSUE THREAD

**Issue by nschoenwald** [Gundancer/foundryvtt-token-color-marker#1]
Using current V10 of foundry and current version of the module.

Color icon can't be replaced, following error messages are shown in dev console and when adding a new color:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/72390280/195959135-4b766872-6248-4431-b3b4-a9eb2e32622a.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/72390280/195959064-b0966e46-5541-4a78-948d-c0758daee561.png">

**Comment by Gundancer** [comment]
Thank you for reporting this issue. This should now be fixed in the new version 2.2.2. 

Note: the first time loading after the update to v2.2.2, similar errors may still occur and the colors will not show correctly. refreshing the scene should clear this up.
