### ISSUE TITLE
Error in Foundry V11.302 (with dnd5e 2.2.1)

### ISSUE THREAD

**Issue by nschoenwald** [Gundancer/foundryvtt-token-color-marker#4]
<img width="518" alt="image" src="https://github.com/Gundancer/foundryvtt-token-color-marker/assets/72390280/8e62f6e6-c9db-4b4e-9293-1b9c6444cc09">

**Comment by Gundancer** [comment]
This is fixed with the latest update.

**Comment by nschoenwald** [comment]
Thank you! :)
