### ISSUE TITLE
Module Shows Wrong Token Marker

### ISSUE THREAD

**Issue by kajishun** [Gundancer/foundryvtt-token-color-marker#5]
I love this mod- Simple color markers when that is all you need. I'm trying to figure out why I receive only a Caution Triangle with Exclamation Mark whenever I try to use it. Please advise. Thank you!

![image](https://github.com/Gundancer/foundryvtt-token-color-marker/assets/60208624/89b13048-edea-40fa-a0ee-8977ad478353)

**Comment by Gundancer** [comment]
To help track down the issue, what foundry version are you using? What game system and version are you using?

**Comment by kajishun** [comment]
apologies, i forgot to add those details. FVTT v10.291, D&D 5e 2.2.1, Mod
2.2.4.

i plan to try again with find the culprit soon. i thought i did that before
with this mod. as i can't recall the results i'll do it again.

**Comment by Gundancer** [comment]
Everything seems to be working on my end when I try those versions. from your screen shot it looks like it is not able to find the .webp image files. They are located in "token-color-marker" folder in the world data. Something like: "FoundryVTT\Data\worlds\<world name>\token-color-marker". 

I am able to see the same issue if I delete that folder. However, when a gamemaster connects to the game it creates that folder, if it does not exist, and creates the color images. A possible fix is logging in with the gamemaster account then refreshing to see if the colors show properly.

Did the module work for you in the past? Have the world files been moved or changed?  Are you getting any errors in dev tools related to creating the "token-color-marker" folder?

**Comment by kajishun** [comment]
i am using Forge VTT, not my own Foundry VTT server. (at this time; that
may change in the future.)

in Forge VTT i currently see modules/token-color-marker with 5 directories
class~ templates. i do not see a token-color-marker folder in any of my
several worlds. as i recall, this module has never worked for me in the
past.

i ran find the culprit as well just to test and foundry told me that the
issue is token color marker. i realize that the seemingly incorrect
directories could be the actual cause. i ran FTC to rule out any other
issues. it found no other issues and claimed that TCM was the cause.

i then looked into copying the TCM folder into my dev world and... well, i
cannot seem to do so in Forge. i asked in their Discord how to do so. the
help on Forge VTT Discord claimed, "In general if a module needs a folder
you can make it in your assets library  https://forge-vtt.com/assets/browse
and it will just work." i went to do so when i noticed that Forge VTT
seemed to auto-create the folder. yet i still have the same issue.

i am starting to think this is a Forge VTT specific issue. thoughts?

**Comment by kajishun** [comment]
FVTT 10.291 (can't really upgrade yet due to mods)
DnD5e 2.2.2

i caught this in the error log several times:

IconManager.mjs:52  Uncaught (in promise) Directory
worlds/kantcon-2023-cs/token-color-marker does not exist or is not
accessible in this storage location

**Comment by Gundancer** [comment]
I messaged on the forge discord and this seems to be a permissions issue where the module can not create a folder in a users "asset library". I am working with them to see if I can resolve this issue. In the meantime, if it is possible to manually create the "token-color-marker" folder at that location: "worlds/kantcon-2023-cs/token-color-marker". That should work as a temporary fix for your forge server.

**Comment by Gundancer** [comment]
This has been fixed for both Foundry v10 and v11 with module versions 2.2.5 and 3.0.2.

**Comment by kajishun** [comment]
Sweet, thank you!
