### ISSUE TITLE
Module not working with DnD5E 3.0 update (Foundry 11 build 315)

### ISSUE THREAD

**Issue by Airwrecker** [Gundancer/foundryvtt-token-color-marker#6]
Using Foundry 11 build 315 

After updating the Dnd5E game system to 3.0, I can't assign colours to tokens. I can still open up the colour menu and create new colour markers though.

**Comment by Gundancer** [comment]
This has been fixed, please update to module version 3.0.3.

**Comment by Airwrecker** [comment]
Thank you!
