### ISSUE TITLE
Compatibility with dnd5e 3.1

### ISSUE THREAD

**Issue by nschoenwald** [Gundancer/foundryvtt-token-color-marker#7]
I get this error after updating to dnd5e 3.1:
<img width="606" alt="image" src="https://github.com/Gundancer/foundryvtt-token-color-marker/assets/72390280/1e2d0756-fb01-4206-90b3-8088e716127d">

**Comment by Gundancer** [comment]
This has been fixed, please update to module version 3.0.4.
