### ISSUE TITLE
Color picker no longer works in Foundry v12

### ISSUE THREAD

**Issue by GravityBlade** [Gundancer/foundryvtt-token-color-marker#8]
When trying to pick a color I get the following error in console:
![image](https://github.com/user-attachments/assets/6d37a72f-f1b6-4970-bae3-0b34521bde22)
![image](https://github.com/user-attachments/assets/1da300f0-e6cb-4d82-b0d5-cf7e43934a29)

Please review. Thanks.

**Comment by Gundancer** [comment]
This has been fixed, please update to module version 3.0.5.
