### ISSUE TITLE
Token Color Add/Remove Issues

### ISSUE THREAD

**Issue by kajishun** [Gundancer/foundryvtt-token-color-marker#9]
FVTT 12.330, D&D 3.3.1, TCM 4.0.0

Two issues with using TCM:
- If I add/remove quickly, the system recognizes less than the number that I added/removed.
- Colors show properly on token, but not in chat. Chat shows only a neutral, gray icon with no color information

Adding last console info and a screenshot in case they are useful. I recognize that the module says updated for 12.238. Is that the reason this is not working on 12.330?

![image](https://github.com/user-attachments/assets/440b1614-1ba1-47ef-88a5-f33c4b1b235e)
![image](https://github.com/user-attachments/assets/7c7e916d-50f4-46a6-af54-9c9bdff9d4b3)

**Comment by Gundancer** [comment]
Those errors seem to be from a different module. I am testing with FVTT 12.330 and D&D 3.3.1. I am not able to reproduce the issue of adding and removing quickly. How do you get the condition changes in chat? Is this module? if so, what name and version do you have?

**Comment by kajishun** [comment]
ahah, i had not considered that although i should have. after running FTC!
i found that Condition Lab & Triggler is the conflicting module in
question. both that one and yours are killer mods for me so i can't just
remove either one. i suppose the add and removing quickly is part of the
conflict as it worked properly previously.

**Comment by kajishun** [comment]
My apologies! Yes, I meant to post this for module Token Aura Ring.
